# Generated by Django 5.1.6 on 2025-02-26 23:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AdminTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('can_configure_ambient', models.BooleanField()),
                ('can_gerenciate_members', models.BooleanField()),
                ('can_register_resources', models.BooleanField()),
                ('can_run_atribuition', models.BooleanField()),
                ('can_run_alocation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number_of_students', models.IntegerField()),
                ('num_uses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('classroom_capacity', models.IntegerField()),
                ('num_uses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('num_uses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('num_uses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('column', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('column', models.IntegerField()),
                ('Activitie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.activitie')),
            ],
        ),
        migrations.AddField(
            model_name='activitie',
            name='tclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.class'),
        ),
        migrations.CreateModel(
            name='Class_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_weight', models.FloatField()),
                ('tclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.class')),
            ],
        ),
        migrations.AddField(
            model_name='activitie',
            name='tclassroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.classroom'),
        ),
        migrations.CreateModel(
            name='Classroom_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_weight', models.FloatField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='ideal_classrooms',
            field=models.ManyToManyField(to='AllokAcads.classroom_preference'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.classroomtp'),
        ),
        migrations.CreateModel(
            name='Formation_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_weight', models.FloatField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=40)),
                ('time_in_campus', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('time_in_institution', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('career_level', models.CharField(max_length=40)),
                ('is_professor', models.BooleanField(default=False)),
                ('max_actv_in_cicle', models.IntegerField()),
                ('min_actv_in_cicle', models.IntegerField()),
                ('max_actv_in_day', models.IntegerField()),
                ('min_actv_in_day', models.IntegerField()),
                ('subjects_weight', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('num_uses', models.IntegerField()),
                ('admin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.admintp')),
                ('prefered_classes', models.ManyToManyField(to='AllokAcads.class_preference')),
                ('prefered_classrooms', models.ManyToManyField(to='AllokAcads.classroom_preference')),
            ],
        ),
        migrations.AddField(
            model_name='activitie',
            name='tprofessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.member'),
        ),
        migrations.CreateModel(
            name='Member_Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_experience_time', models.IntegerField()),
                ('didactic_experience_time', models.IntegerField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.formation')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='formations',
            field=models.ManyToManyField(to='AllokAcads.member_formation'),
        ),
        migrations.CreateModel(
            name='Professor_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_weight', models.FloatField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.member')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='favorite_professors',
            field=models.ManyToManyField(to='AllokAcads.professor_preference'),
        ),
        migrations.AddField(
            model_name='member',
            name='prefered_schedules',
            field=models.ManyToManyField(to='AllokAcads.schedule_preference'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='prefered_schedules',
            field=models.ManyToManyField(to='AllokAcads.schedule_preference'),
        ),
        migrations.AddField(
            model_name='class',
            name='prefered_schedules',
            field=models.ManyToManyField(to='AllokAcads.schedule_preference'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('num_uses', models.IntegerField()),
                ('favorite_professors', models.ManyToManyField(to='AllokAcads.professor_preference')),
                ('ideal_classrooms', models.ManyToManyField(to='AllokAcads.classroom_preference')),
                ('relevant_formations', models.ManyToManyField(to='AllokAcads.formation_preference')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='necessary_subjects',
            field=models.ManyToManyField(to='AllokAcads.subject'),
        ),
        migrations.AddField(
            model_name='activitie',
            name='tsubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.subject'),
        ),
        migrations.CreateModel(
            name='Subject_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_weight', models.FloatField()),
                ('periods', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.subject')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='prefered_subjects',
            field=models.ManyToManyField(to='AllokAcads.subject_preference'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines_number', models.IntegerField()),
                ('columns_number', models.IntegerField()),
                ('alt_solicitations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), size=None)),
                ('quality_rate', models.FloatField()),
                ('table', models.ManyToManyField(to='AllokAcads.alocation')),
            ],
        ),
        migrations.CreateModel(
            name='Ambient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=60)),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=500)),
                ('periods_in_a_day', models.IntegerField()),
                ('days_ins_a_cicle', models.IntegerField()),
                ('breaks', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('enter_solicitations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9), size=None)),
                ('form_opening', models.DateField()),
                ('form_closing', models.DateField()),
                ('alt_solicitations_opening', models.DateField()),
                ('alt_solicitations_closing', models.DateField()),
                ('max_actv_in_cicle', models.IntegerField()),
                ('min_actv_in_cicle', models.IntegerField()),
                ('max_actv_in_day', models.IntegerField()),
                ('min_actv_in_day', models.IntegerField()),
                ('activities', models.ManyToManyField(to='AllokAcads.activitie')),
                ('classes', models.ManyToManyField(to='AllokAcads.class')),
                ('classrooms', models.ManyToManyField(to='AllokAcads.classroom')),
                ('formations', models.ManyToManyField(to='AllokAcads.formation')),
                ('members', models.ManyToManyField(to='AllokAcads.member')),
                ('subjects', models.ManyToManyField(to='AllokAcads.subject')),
                ('edit_timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_timetable', to='AllokAcads.timetable')),
                ('published_timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_timetable', to='AllokAcads.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='Unregistered_Activitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=400)),
                ('activitie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.activitie')),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='not_alocated',
            field=models.ManyToManyField(related_name='not_alocated', to='AllokAcads.unregistered_activitie'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='not_atribuited',
            field=models.ManyToManyField(related_name='not_atribuited', to='AllokAcads.unregistered_activitie'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=20)),
                ('birthdate', models.DateField()),
                ('password', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('picture', models.ImageField(upload_to='')),
                ('ambients', models.ManyToManyField(to='AllokAcads.ambient')),
                ('invitations', models.ManyToManyField(to='AllokAcads.invitation')),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to='AllokAcads.user'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='inviting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviting_user', to='AllokAcads.user'),
        ),
    ]
