# Generated by Django 5.2.3 on 2025-06-26 07:55

import AllokAcads.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_weight', models.FloatField(null=True)),
                ('professor_weight', models.FloatField(null=True)),
                ('activities_qtd', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('can_configure_ambient', models.BooleanField()),
                ('can_gerenciate_members', models.BooleanField()),
                ('can_register_resources', models.BooleanField()),
                ('can_run_atribuition', models.BooleanField()),
                ('can_run_alocation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number_of_students', models.IntegerField()),
                ('num_uses', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('classroom_capacity', models.IntegerField()),
                ('num_uses', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('num_uses', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('num_uses', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('column', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('column', models.IntegerField()),
                ('activitie', models.ManyToManyField(related_name='activitie', to='AllokAcads.activitie')),
            ],
        ),
        migrations.AddField(
            model_name='activitie',
            name='tclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AllokAcads.class'),
        ),
        migrations.CreateModel(
            name='Class_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_weight', models.FloatField(default=0)),
                ('tclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.class')),
            ],
        ),
        migrations.AddField(
            model_name='activitie',
            name='tclassroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AllokAcads.classroom'),
        ),
        migrations.CreateModel(
            name='Classroom_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_weight', models.FloatField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='ideal_classrooms',
            field=models.ManyToManyField(to='AllokAcads.classroom_preference'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AllokAcads.classroomtp'),
        ),
        migrations.CreateModel(
            name='Ambient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambientid', models.CharField(blank=True, max_length=9, null=True)),
                ('name', models.CharField(max_length=60)),
                ('picture', models.ImageField(null=True, upload_to=AllokAcads.models.ambient_image_path)),
                ('description', models.TextField(max_length=500, null=True)),
                ('periods_in_a_day', models.IntegerField(null=True)),
                ('days_in_a_cicle', models.IntegerField(null=True)),
                ('breaks', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None), null=True, size=None)),
                ('enter_solicitations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9), blank=True, default=list, null=True, size=None)),
                ('form_opening', models.DateField(null=True)),
                ('form_closing', models.DateField(null=True)),
                ('alt_solicitations_opening', models.DateField(null=True)),
                ('alt_solicitations_closing', models.DateField(null=True)),
                ('max_actv_in_cicle', models.IntegerField(null=True)),
                ('min_actv_in_cicle', models.IntegerField(null=True)),
                ('max_actv_in_day', models.IntegerField(null=True)),
                ('min_actv_in_day', models.IntegerField(null=True)),
                ('activities', models.ManyToManyField(to='AllokAcads.activitie')),
                ('admin_types', models.ManyToManyField(to='AllokAcads.admintp')),
                ('classes', models.ManyToManyField(to='AllokAcads.class')),
                ('classrooms', models.ManyToManyField(to='AllokAcads.classroom')),
                ('classroom_types', models.ManyToManyField(to='AllokAcads.classroomtp')),
                ('formations', models.ManyToManyField(to='AllokAcads.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Formation_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_weight', models.FloatField(default=0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_accept', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('ambient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_ambient', to='AllokAcads.ambient')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(default='', max_length=40, null=True)),
                ('time_in_campus', models.IntegerField(default=0, null=True)),
                ('time_in_institution', models.IntegerField(default=0, null=True)),
                ('is_professor', models.BooleanField(default=False)),
                ('num_uses', models.IntegerField(default=0, null=True)),
                ('admin_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AllokAcads.admintp')),
                ('prefered_classes', models.ManyToManyField(to='AllokAcads.class_preference')),
                ('prefered_classrooms', models.ManyToManyField(to='AllokAcads.classroom_preference')),
            ],
        ),
        migrations.AddField(
            model_name='ambient',
            name='members',
            field=models.ManyToManyField(to='AllokAcads.member'),
        ),
        migrations.AddField(
            model_name='activitie',
            name='tprofessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AllokAcads.member'),
        ),
        migrations.CreateModel(
            name='Member_Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_experience_time', models.IntegerField()),
                ('didactic_experience_time', models.IntegerField()),
                ('formation_degree', models.TextField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.formation')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='formations',
            field=models.ManyToManyField(to='AllokAcads.member_formation'),
        ),
        migrations.CreateModel(
            name='Professor_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_weight', models.FloatField(default=0)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.member')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='favorite_professors',
            field=models.ManyToManyField(to='AllokAcads.professor_preference'),
        ),
        migrations.AddField(
            model_name='member',
            name='occupated_schedules',
            field=models.ManyToManyField(related_name='occupated', to='AllokAcads.schedule_preference'),
        ),
        migrations.AddField(
            model_name='member',
            name='prefered_schedules',
            field=models.ManyToManyField(to='AllokAcads.schedule_preference'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='occupated_schedules',
            field=models.ManyToManyField(to='AllokAcads.schedule_preference'),
        ),
        migrations.AddField(
            model_name='class',
            name='prefered_schedules',
            field=models.ManyToManyField(to='AllokAcads.schedule_preference'),
        ),
        migrations.AddField(
            model_name='ambient',
            name='available_schedules',
            field=models.ManyToManyField(to='AllokAcads.schedule_preference'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('num_uses', models.IntegerField(default=0, null=True)),
                ('favorite_professors', models.ManyToManyField(to='AllokAcads.professor_preference')),
                ('ideal_classrooms', models.ManyToManyField(to='AllokAcads.classroom_preference')),
                ('relevant_formations', models.ManyToManyField(to='AllokAcads.formation_preference')),
            ],
        ),
        migrations.AddField(
            model_name='ambient',
            name='subjects',
            field=models.ManyToManyField(to='AllokAcads.subject'),
        ),
        migrations.AddField(
            model_name='activitie',
            name='tsubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AllokAcads.subject'),
        ),
        migrations.CreateModel(
            name='Subject_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_weight', models.FloatField(default=0)),
                ('occupation', models.IntegerField(null=True)),
                ('periods', models.IntegerField(null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.subject')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='prefered_subjects',
            field=models.ManyToManyField(to='AllokAcads.subject_preference'),
        ),
        migrations.AddField(
            model_name='class',
            name='necessary_subjects',
            field=models.ManyToManyField(to='AllokAcads.subject_preference'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines_number', models.IntegerField(null=True)),
                ('columns_number', models.IntegerField(null=True)),
                ('alt_solicitations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), null=True, size=None)),
                ('quality_rate', models.FloatField(null=True)),
                ('table', models.ManyToManyField(to='AllokAcads.alocation')),
            ],
        ),
        migrations.AddField(
            model_name='ambient',
            name='edit_timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_timetable', to='AllokAcads.timetable'),
        ),
        migrations.AddField(
            model_name='ambient',
            name='published_timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_timetable', to='AllokAcads.timetable'),
        ),
        migrations.CreateModel(
            name='Unregistered_Activitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=400, null=True)),
                ('activitie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.activitie')),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='not_alocated',
            field=models.ManyToManyField(related_name='not_alocated', to='AllokAcads.unregistered_activitie'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='not_atribuited',
            field=models.ManyToManyField(related_name='not_atribuited', to='AllokAcads.unregistered_activitie'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=9, null=True)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('description', models.TextField(max_length=500, null=True)),
                ('picture', models.ImageField(null=True, upload_to=AllokAcads.models.user_image_path)),
                ('ambients', models.ManyToManyField(to='AllokAcads.ambient')),
                ('invitations', models.ManyToManyField(related_name='invitations', to='AllokAcads.invitation')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.user'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_user', to='AllokAcads.user'),
        ),
    ]
