# Generated by Django 5.1.6 on 2025-03-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambient',
            old_name='days_ins_a_cicle',
            new_name='days_in_a_cicle',
        ),
    ]
