# Generated by Django 5.1.6 on 2025-03-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0002_rename_days_ins_a_cicle_ambient_days_in_a_cicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomtp',
            name='num_uses',
            field=models.IntegerField(null=True),
        ),
    ]
