# Generated by Django 5.1.6 on 2025-03-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0003_alter_classroomtp_num_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambient',
            name='classrooms_types',
            field=models.ManyToManyField(to='AllokAcads.classroomtp'),
        ),
    ]
