# Generated by Django 5.1.6 on 2025-03-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0004_ambient_classrooms_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambient',
            old_name='classrooms_types',
            new_name='classroom_types',
        ),
    ]
