# Generated by Django 5.1.6 on 2025-03-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0005_rename_classrooms_types_ambient_classroom_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='num_uses',
            field=models.IntegerField(null=True),
        ),
    ]
