# Generated by Django 5.1.6 on 2025-03-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0006_alter_formation_num_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='num_uses',
            field=models.IntegerField(null=True),
        ),
    ]
