# Generated by Django 5.1.6 on 2025-03-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0007_alter_subject_num_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='num_uses',
            field=models.IntegerField(null=True),
        ),
    ]
