# Generated by Django 5.1.6 on 2025-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0008_alter_classroom_num_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='num_uses',
            field=models.IntegerField(null=True),
        ),
    ]
