# Generated by Django 5.1.6 on 2025-03-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0009_alter_class_num_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambient',
            name='available_schedules',
            field=models.ManyToManyField(to='AllokAcads.schedule_preference'),
        ),
    ]
