# Generated by Django 5.1.6 on 2025-03-31 00:20

import AllokAcads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0010_ambient_available_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='prefered_schedules',
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to=AllokAcads.models.user_image_path),
        ),
    ]
