# Generated by Django 5.1.6 on 2025-04-08 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0011_remove_classroom_prefered_schedules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='inviting_user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='max_actv_in_cicle',
        ),
        migrations.RemoveField(
            model_name='member',
            name='max_actv_in_day',
        ),
        migrations.RemoveField(
            model_name='member',
            name='min_actv_in_cicle',
        ),
        migrations.RemoveField(
            model_name='member',
            name='min_actv_in_day',
        ),
        migrations.AddField(
            model_name='invitation',
            name='ambient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_ambient', to='AllokAcads.ambient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='to_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_user', to='AllokAcads.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='invitations',
            field=models.ManyToManyField(related_name='invitations', to='AllokAcads.invitation'),
        ),
    ]
