# Generated by Django 5.1.6 on 2025-04-09 00:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0012_remove_invitation_invited_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambient',
            name='enter_solicitations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9), blank=True, default=list, null=True, size=None),
        ),
    ]
