# Generated by Django 5.1.6 on 2025-04-09 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0013_alter_ambient_enter_solicitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='admin_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.admintp'),
        ),
    ]
