# Generated by Django 5.1.6 on 2025-04-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0014_alter_member_admin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='tclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.class'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='tclassroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.classroom'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='tprofessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.member'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='tsubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.subject'),
        ),
    ]
