# Generated by Django 5.1.6 on 2025-04-24 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0015_alter_activitie_tclass_alter_activitie_tclassroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='tclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.class_preference'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='tclassroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.classroom_preference'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='tprofessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.professor_preference'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='tsubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.subject_preference'),
        ),
    ]
