# Generated by Django 5.1.6 on 2025-04-24 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0016_alter_activitie_tclass_alter_activitie_tclassroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitie',
            name='classroom_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='tclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.class'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='tclassroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.classroom'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='tprofessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.member'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='tsubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AllokAcads.subject'),
        ),
    ]
