# Generated by Django 5.1.6 on 2025-04-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0017_activitie_classroom_weight_alter_activitie_tclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_preference',
            name='occupation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='necessary_subjects',
            field=models.ManyToManyField(to='AllokAcads.subject_preference'),
        ),
    ]
