# Generated by Django 5.2.1 on 2025-05-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0018_subject_preference_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='career_level',
        ),
        migrations.AddField(
            model_name='activitie',
            name='activities_qtd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activitie',
            name='professor_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='member_formation',
            name='formation_degree',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitie',
            name='classroom_weight',
            field=models.FloatField(null=True),
        ),
    ]
