# Generated by Django 5.2.1 on 2025-06-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllokAcads', '0019_remove_member_career_level_activitie_activities_qtd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_preference',
            name='periods',
            field=models.IntegerField(null=True),
        ),
    ]
